name: Lodestar

on:
  schedule:
    # Run once daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-lodestar-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Clone client repo
      run: git clone https://github.com/GabrielAstieres/lodestar.git -b feat/generated-nightly-vectors

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        check-latest: true

    - name: Download nightly test vectors
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd lodestar
        yarn install --frozen-lockfile
        yarn download-spec-tests-nightly

    - name: Delete old test reports
      run: rm -rf docs/reports/lodestar

    - name: Run tests
      run: |
        mkdir -p docs/reports/lodestar
        cd lodestar/packages/beacon-node
        yarn build

        start=$(date +%s.%N)
        if yarn test:spec > ../docs/reports/lodestar/test.txt 2>&1; then
          echo "TEST_SUCCESS=true" >> "$GITHUB_ENV"
        else
          echo "TEST_SUCCESS=false" >> "$GITHUB_ENV"
        fi
        end=$(date +%s.%N)
        duration=$(echo "$end - $start" | bc)
        echo "TEST_DURATION=${duration}" >> "$GITHUB_ENV"

    - name: Summarize
      run: python3 scripts/make_lodestar_summary.py

    - name: Commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git fetch origin

        git add docs/reports/lodestar
        git add docs/summaries/lodestar.json
        if git diff --cached --quiet; then
          echo "No changes to commit"
          exit 0
        fi

        git commit -m "Update lodestar status"
        for i in {1..5}; do
          git pull --rebase origin HEAD && \
          git push && break || {
            echo "Push failed, retrying in 5s..."
            sleep 5
          }
        done