name: Teku

on:
  schedule:
    # Run once daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-teku-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Clone client repo
      run: git clone https://github.com/consensys/teku.git

    - name: Download reference tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd teku
        NIGHTLY=true ./gradlew expandRefTests

    - name: Run reference tests
      run: |
        cd teku
        ./gradlew referenceTest || true

    - name: Copy teku HTML report
      run: |
        rm -rf docs/reports/teku
        mkdir -p docs/reports/teku
        cp -r teku/eth-reference-tests/build/reports/tests/referenceTest/* docs/reports/teku/

    - name: Extract summary from HTML report
      run: |
        pip install beautifulsoup4
        python3 scripts/make_teku_summary.py

    - name: Commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add docs/reports/teku
        git add docs/summaries/teku.json
        git commit -m "Update teku status" || echo "No changes to commit"
        git push